FROM python:3.8-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./db ./db
COPY ./listener ./listener
COPY ./shared ./shared
COPY ./main_listener.py ./main_listener.py

CMD [ "python3", "main_listener.py" ]